#!/bin/bash

ANALYSISDIR="$HOME/IGM_SARSCOV2/ANALYSIS"

echo "" && echo "Output path: $HOME/IGM_SARSCOV2/ANALYSIS"
echo "" && echo "Coverage plot: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_coverage.pdf"
echo "Fasta consensus: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_consensus.fasta"
echo "Statistics + Pangolin + Nextclade: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_summary.txt"
echo "" && echo "Log Analysis: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_log_summary_"$(date +'%Y-%m-%d')".txt"

[ ! -d "$ANALYSISDIR" ] && mkdir "$ANALYSISDIR"

bg() {

    start=$(date +%s.%N)

    RAWDIR=$PWD

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p' | awk '{print $1-2}')

    DATE="$(date +'%Y-%m-%d')"

    if [ -z "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt ]; then
        echo "SampleId#NumberTotalReads#NumberReadsMapped#AverageDepth#Depth10x#Depth100x#Depth1000x#ReferenceCoverage#NCount#PangoLineage#Clade#Substitutions#Deletions#Insertions#Missing#aaSubstitutions#aaDeletions" | \
            tr '#' '\t' > "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
    fi

    for i in $(find "$ANALYSISDIR" -type d -name "*.results" | awk -F/ '{print $NF}' |  awk -F. '{print $1}' | sort -u); do
        source activate igm_sarscov2
        echo -n "$i""#" | tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        samtools view -c "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        samtools view -c -h -F 4 "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        samtools depth "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{sum+=$3} END {print sum/NR}' | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        paste <(samtools depth "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{if ($3 > '"10"') {print $0}}' | wc -l) \
            <(fastalength $HOME/IGM_SARSCOV2/NC_045512.2.fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        paste <(samtools depth "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{if ($3 > '"100"') {print $0}}' | wc -l) \
            <(fastalength $HOME/IGM_SARSCOV2/NC_045512.2.fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        paste <(samtools depth "$ANALYSISDIR"/"$i".results/"$i".sorted.bam | awk '{if ($3 > '"1000"') {print $0}}' | wc -l) \
            <(fastalength $HOME/IGM_SARSCOV2/NC_045512.2.fasta | awk '{print $1}') | awk -F"\t" '{printf("%0.2f\n", $1/$2*100)}' | \
            awk '{printf $0"#"}' | tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        paste <(fastalength $HOME/IGM_SARSCOV2/NC_045512.2.fasta | awk '{print $1}') \
            <(seqtk comp "$ANALYSISDIR"/"$i".results/"$i".depth10.fa | awk -F"\t" '{print $9}') | \
            awk -F"\t" '{printf("%0.2f\n", ($1-$2)/$1*100)}' | awk '{printf $0"#"}' | tr '#' '\t' \
            >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        seqtk comp "$ANALYSISDIR"/"$i".results/"$i".depth10.fa | awk -F"\t" '{print $9}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        cat "$ANALYSISDIR"/"$i".results/"$i".depth10.fa.algn.minor.fa >> "$ANALYSISDIR"/preconsensus.tmp
        cat "$ANALYSISDIR"/"$i".results/"$i".depth10.fa >> "$ANALYSISDIR"/preconsensus.tmp
        source activate pangolin
        pangolin "$ANALYSISDIR"/"$i".results/"$i".depth10.fa -t "$THREADS" --outfile "$ANALYSISDIR"/"$i".results/"$i".lineage_report.csv
        cat "$ANALYSISDIR"/"$i".results/"$i".lineage_report.csv | sed -n 2p | awk -F, '{print $2}' | awk '{printf $0"#"}' | \
            tr '#' '\t' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        source activate nextclade
        nextclade -i "$ANALYSISDIR"/"$i".results/"$i".depth10.fa -j "$THREADS" -c "$ANALYSISDIR"/"$i".results/"$i".nextclade.csv
        cat "$ANALYSISDIR"/"$i".results/"$i".nextclade.csv | sed -n 2p | tr ";" "\t" | awk -F"\t" '{print $2"\t"$11"\t"$12"\t"$13"\t"$14"\t"$17"\t"$19}' | \
            awk '{printf $0"#"}' | tr '#' '\n' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_summary.txt
        source activate plot
        fastcov.py -l "$ANALYSISDIR"/"$i".results/"$i".sorted.bam -o "$ANALYSISDIR"/"$i".results/"$i".coverage.pdf
    done

    gs -dSAFER -r3000 -sDEVICE=pdfwrite -dNOPAUSE -dBATCH \
        -sOUTPUTFILE="$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_coverage.pdf "$ANALYSISDIR"/*.results/*.pdf

    source activate igm_sarscov2

    mafft --thread "$THREADS" --quiet --auto --keeplength --inputorder --6merpair --leavegappyregion \
        --addfragments "$ANALYSISDIR"/preconsensus.tmp $HOME/IGM_SARSCOV2/NC_045512.2.fasta | \
        seqkit grep -vip NC_045512.2 | sed '/>/!y/atcgn-/ATCGNN/' >> "$ANALYSISDIR"/"$(pwd | awk -F/ '{print $NF}')"_consensus.fasta

    rm -rf "$ANALYSISDIR"/*.tmp

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was $runtime seconds." && echo ""

}

bg &>>$ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_log_summary_"$(date +'%Y-%m-%d')".txt &
