#!/bin/bash

PRIMERSCHEME=$1

ANALYSISDIR="$HOME/IGM_SARSCOV2/ANALYSIS"

echo "" && echo "Output path: $HOME/IGM_SARSCOV2/ANALYSIS"
echo "" && echo "RAW fastq.gz folder info: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_folder_info.txt"
echo "" && echo "Log Analysis: $ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_log_assembly_"$(date +'%Y-%m-%d')".txt"

[ ! -d "$ANALYSISDIR" ] && mkdir "$ANALYSISDIR"

chmod 700 -R "$ANALYSISDIR"

bg() {

    start=$(date +%s.%N)

    DEPTH="10"

    MINLEN="75"

    RAWDIR=$PWD

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p' | awk '{print $1-2}')

    echo "folder#read" | tr '#' '\t' > "$ANALYSISDIR"/"$(echo $PWD | awk -F'/' '{print $NF}')_folder_info.txt"

    find ./ -type f -name "*.fastq.gz" | awk -F'/' '{print $(NF-1),$NF}' | tr '[:blank:]' '\t' | \
        awk '/.fastq.gz/d' >> "$ANALYSISDIR"/"$(echo $PWD | awk -F'/' '{print $NF}')_folder_info.txt"

    for i in $(find ./ -type f -name "*R1*"); do
        cp "$i" "$ANALYSISDIR"/"$(echo "$i" | awk -F'/' '{print $(NF-1)}' | awk -F"-|_" '{print $1}')"_R1.fastq.gz -v
    done

    for i in $(find ./ -type f -name "*R2*"); do
        cp "$i" "$ANALYSISDIR"/"$(echo "$i" | awk -F'/' '{print $(NF-1)}' | awk -F"-|_" '{print $1}')"_R2.fastq.gz -v
    done

    source activate igm_sarscov2

    for i in $(find "$ANALYSISDIR" -type f -name "*.fastq.gz" | awk -F/ '{print $NF}' | awk -F_ '{print $1}' | sort -u); do
        bash sars2_assembly $HOME/IGM_SARSCOV2/NC_045512.2.fasta "$ANALYSISDIR"/"$i"_R1.fastq.gz "$ANALYSISDIR"/"$i"_R2.fastq.gz \
            "$i" "$THREADS" "$DEPTH" "$MINLEN" $HOME/IGM_SARSCOV2/"$PRIMERSCHEME".fasta "$ANALYSISDIR"
    done

    rm -rf "$ANALYSISDIR"/*.fastq.gz

    end=$(date +%s.%N)

    runtime=$(python -c "print(${end} - ${start})")

    echo "" && echo "Done. The runtime was $runtime seconds." && echo ""

}

bg &>>$ANALYSISDIR/"$(pwd | awk -F/ '{print $NF}')"_log_assembly_"$(date +'%Y-%m-%d')".txt &
