#!/bin/bash

mamba update -y -n igm_sarscov2 -c conda-forge -c anaconda -c bioconda -c defaults --all

mamba update -y -n nextclade -c conda-forge -c anaconda -c bioconda -c defaults --all

mamba update -y -n plot -c conda-forge -c anaconda -c bioconda -c defaults --all

source activate pangolin
pangolin --update
