#!/bin/bash

bg() {

    THREADS=$(lscpu | grep 'CPU(s):' | awk '{print $2}' | sed -n '1p')

    INPUT=$1

    OUTPUT=$(basename ${INPUT%.*})

    DATE=$(date +'%Y-%m-%d')

    source activate pangolin

    pangolin $INPUT -t $THREADS --outfile pangolin.tmp

    cat pangolin.tmp | (sed -u 1q; sort) | sed -e 's/\,/\t/g' > $OUTPUT.pangolin_$DATE.txt

    rm pangolin.tmp

}

bg $1 >/dev/null 2>&1 &
