#!/bin/bash

source activate pangolin
pangolin --update
pangolin -v
pangolin -pv

# source activate pangolin
# git pull
# python setup.py install
# conda env update -f environment.yml
# pip install git+https://github.com/cov-lineages/pangoLEARN.git --upgrade
# pangolin -v
# pangolin -pv
