#!/bin/bash

PRIMERSCHEME="$1"

bg() {

    "$HOME"/IGM_SARSCOV2/scripts/igm_sarscov2_update

    while [ ! -z "$(pgrep igm_sarscov2_up)" ]; do
        sleep 2
    done

    "$HOME"/IGM_SARSCOV2/scripts/igm_sarscov2_assembly "$PRIMERSCHEME"

    while [ ! -z "$(pgrep igm_sarscov2_as)" ]; do
        sleep 2
    done

    "$HOME"/IGM_SARSCOV2/scripts/igm_sarscov2_summary

}

bg "$1" &
