#!/bin/bash

bg() {

    mamba update -y -n base -c conda-forge -c anaconda -c bioconda -c defaults conda
    mamba update -y -n igm-sars2_assembly -c conda-forge -c anaconda -c bioconda -c defaults --all
    mamba update -y -n igm-sars2_summary -c conda-forge -c anaconda -c bioconda -c defaults --all
    source activate igm-sars2_summary
    pangolin --update

}

bg &>>$HOME/IGM_SARSCOV2/UpdateDependencies_$(uname -n)_$(date +'%Y-%m-%d').txt &
